# Generated by Django 3.0.8 on 2021-08-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectinvitationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinvitationtoken',
            options={'default_related_name': 'project_invitation_set'},
        ),
        migrations.AlterField(
            model_name='projectinvitationtoken',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invitation_set', to='projects.Project'),
        ),
    ]
